const CustomButton = {
  key: require('./button/key.png'),
  key1: require('./button/key1.png'),
  l2: require('./button/l2.png'),
  shuffle: require('./button/shuffle.png'),
  buttonOff: require('./button/buttonOff.png'),
  buttonOn: require('./button/buttonOn.png'),
  buttonGrey: require('./button/buttonGrey.png'),
  buttonYellow: require('./button/buttonYellow.png'),
  blueOff: require('./button/blueOff.png'),
  blueOn: require('./button/blueOn.png'),
  reset: require('./button/reset.png'),
  openLetter: require('./button/openLetter.png'),
  openWord: require('./button/openWord.png'),
  help: require('./button/help.png'),
  bonus: require('./button/bonus.png'),
  grid: require('./button/grid.png'),
  label: require('./button/label.png'),
};
export default CustomButton;
