const CustomButton = {
  l2: require('./button/l2.png'),
  shuffle: require('./button/shuffle.png'),
  buttonOff: require('./button/buttonOff.png'),
  buttonOn: require('./button/buttonOn.png'),
  buttonGrey: require('./button/buttonGrey.png'),
  buttonYellow: require('./button/buttonYellow.png'),
  blueOff: require('./button/blueOff.png'),
  blueOn: require('./button/blueOn.png'),
  reset: require('./button/reset.png'),
  openLetter: require('./button/openLetter.png'),
  openWord: require('./button/openWord.png'),
  help: require('./button/help.png'),
  bonus: require('./button/bonus.png'),
  grid: require('./button/grid.png'),
  label: require('./button/label.png'),
  labelNext: require('./button/labelNext.png'),
  progress1: require('./button/progress1.png'),
  progress2: require('./button/progress2.png'),
  settingsBlue: require('./button/settingsBlue.png'),
  setBlue: require('./button/setBlue.png'),
};
export default CustomButton;
